# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atmosphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pAtm', models.FloatField(default=0)),
                ('TAtm', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValuesSubstance', models.FloatField(default=0)),
                ('User', models.CharField(max_length=100)),
                ('T1', models.FloatField(default=0)),
                ('T2', models.FloatField(default=0)),
                ('Nheater', models.FloatField(default=0)),
                ('KPDheater', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cSolid', models.FloatField(default=0)),
                ('cLiquid', models.FloatField(default=0)),
                ('QCond', models.FloatField(default=0)),
                ('TCond', models.FloatField(default=0)),
                ('THeat', models.FloatField(default=0)),
                ('QHeat', models.FloatField(default=0)),
                ('Key', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Surname', models.FloatField(default=0, max_length=100)),
                ('Mail', models.FloatField(default=0, max_length=150)),
                ('Login', models.FloatField(default=0, max_length=100)),
                ('Password', models.FloatField(default=0, max_length=150)),
                ('Category', models.FloatField(default=8, max_length=2)),
            ],
        ),
    ]
