# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-16 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atmosphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pAtm', models.FloatField(default=0)),
                ('TAtm', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('сSolid', models.FloatField(default=0)),
                ('cLiquid', models.FloatField(default=0)),
                ('QCond', models.FloatField(default=0)),
                ('TCond', models.FloatField(default=0)),
                ('THeat', models.FloatField(default=0)),
                ('QHeat', models.FloatField(default=0)),
            ],
        ),
    ]
