# Generated by Django 2.0 on 2017-12-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybergoose', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('SecName', models.CharField(max_length=50)),
                ('Age', models.IntegerField(default=0)),
                ('SurName', models.CharField(max_length=50)),
                ('Form', models.CharField(max_length=50)),
            ],
        ),
    ]
