# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-12 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybergoose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='Q',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='substance',
            name='TCond',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='substance',
            name='THeat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='substance',
            name='c',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='substance',
            name='qBurn',
            field=models.FloatField(default=0),
        ),
    ]
